os: Visual Studio 2017
version: 1.0.0-build{build}
init:
- git config --global core.autocrlf true
install:
- cmd: npm install -g bower
build_script:
- ps: .\build.ps1	
test: off
artifacts:
- path: artifacts/nuget/*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/carable-public/api/v2
  on:
    branch: master
  api_key:
    secure: ilmzDkJLlYFnIB/b2H/kv2VTJrEYN0WVWvIrTquOwealRRuEHst2el/v8UDjWTu7
  skip_symbols: true
